{
 "title": "Grafana Fabric All Base Reference",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PrometheusDataSource", "label": "Prometheus Data Source", "query": "prometheus" },
   { "name": "Environment", "label": "Environment(optional)" },
   { "name": "FabricPort", "label": "FabricPort", "query": "7170" },
   { "name": "LokiDataSource", "label": "Loki Data Source", "query": "loki" },
   { "name": "CassandraPort", "label": "CassandraPort", "query": "9090" },
   { "name": "KafkaPort", "label": "KafkaPort", "query": "9100" }
  ]
 },
 "panels": [
  {
   "title": "Fabric Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fabric Nodes Up",
   "type": "stat",
   "description": "Fabric Nodes Up\nEnter the proper variables on the top side of the dashboard.\nIf needed, Modify the query to return your fabric nodes.\nAlter the Threshold Green Value to the amount of nodes of Fabric.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\".*$FabricPort\", job=\"fabric\", env=\"$Environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fabric Average CPU Usage",
   "type": "stat",
   "description": "Average CPU Usage of the Fabric Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nNode Exporter should be running in order for this metric to work.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100-(avg by(node) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"fabric\", env=\"$Environment\"}[5m]))*100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fabric Average Memory Usage",
   "type": "stat",
   "description": "Average Memory(RAM) Usage of the Fabric Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nNode Exporter should be running in order for this metric to work.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_memory_MemAvailable_bytes{node=~\"fn_.*\", env=\"$Environment\"} * 100) / node_memory_MemTotal_bytes{node=~\"fn_.*\", env=\"$Environment\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fabric Average Heap Usage",
   "type": "stat",
   "description": "Average Heap Memory Usage of the Fabric Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nNode Exporter should be running in order for this metric to work.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{area=\"heap\", instance=~\".*$FabricPort\"}/jvm_memory_bytes_max{area=\"heap\", instance=~\".*$FabricPort\"}*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fabric Performance Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reads Count",
   "type": "stat",
   "description": "Total Number of reads from all Fabric Nodes in last 5 minutes\nThresholds can be set. \nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\nThe \"sum\" at the start of the query can be set to \"min\" or \"max\" or \"avg\" to display different calculations of the values we are receiving from each node.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((increase(com_k2view_fabric_stats_count{ category=\"mdb\", job=\"fabric\", stats=\"mdbFetchBytes\", key!=\"\", env=\"$Environment\"} [5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes Count",
   "type": "stat",
   "description": "Total Number of writes from all Fabric Nodes in last 5 minutes.\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\nThe \"sum\" at the start of the query can be set to \"min\" or \"max\" or \"avg\" to display different calculations of the values we are receiving from each node.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((increase(com_k2view_fabric_stats_count{ category=\"mdb\", job=\"fabric\", stats=\"mdbSaveDuration\", key!=\"\", env=\"$Environment\"} [5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Fetch Time",
   "type": "stat",
   "description": "Average time of mdb Fetches from all Fabric Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving from each node.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg (increase(com_k2view_fabric_stats_total{ category=\"mdb\", job=\"fabric\", stats=\"mdbFetchDuration\", key!=\"\", env=\"$Environment\"} [5m])))/(avg (increase(com_k2view_fabric_stats_count{ category=\"mdb\", job=\"fabric\", stats=\"mdbFetchDuration\", key!=\"\", env=\"$Environment\"} [5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total mDB Size",
   "type": "stat",
   "description": "Total size of all Fabric MDBs from all nodes.\nThresholds can be set.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\nThe \"sum\" at the beginning can be set to either \"max\", \"min\" or \"avg\" in order to display different computations of the values.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((com_k2view_fabric_stats_total{category=\"mdb\",stats=\"mdbSaveBytes\", env=\"$Environment\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Reads Count by LU",
   "type": "piechart",
   "description": "Number of Reads by L.U. in the last 5 minutes.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\n\n",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (key)(increase(com_k2view_fabric_stats_count{ category=\"mdb\", job=\"fabric\", stats=\"mdbFetchDuration\", key!=\"\", env=\"$Environment\"} [5m])))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Average mDB Size",
   "type": "stat",
   "description": "The average size of MDBs across all fabric nodes.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\nThresholds can be set.\nThe \"avg\" at the beginning of the query can be deleted, or set to \"min\"/\"max\" in order to see\nThe average siez of MDBs for each node, or the min/max size across all nodes.",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum by (node)(((com_k2view_fabric_stats_total{category=\"mdb\",stats=\"mdbSaveBytes\", node=~\".*\", env=\"$Environment\"}))))/(sum by (node)((com_k2view_fabric_stats_count{category=\"mdb\", stats=\"mdbSaveBytes\", node=~\".*\", env=\"$Environment\"}))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes Count by LU",
   "type": "piechart",
   "description": "Number of Writes by LU in the last 5 minutes.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\n\n",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (key)(increase(com_k2view_fabric_stats_count{ category=\"mdb\", job=\"fabric\", stats=\"mdbSaveDuration\", key!=\"\", env=\"$Environment\"} [5m])))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total API Calls Count",
   "type": "stat",
   "description": "Total Number of Web Service Calls in the last 5 minutes.\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\n",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((sum by (key) (increase(com_k2view_fabric_stats_count{category=\"transactions\",key=~\"[Kk]2.*\",job=\"fabric\",stats=\"webserviceCalls\", env=\"$Environment\"}[5m]))))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "API Calls Distribution",
   "type": "piechart",
   "description": "Number of Web Service Calls by API, in the last 5 minutes.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\n",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum by (key) (increase(com_k2view_fabric_stats_count{category=\"transactions\",key=~\"[Kk]2.*\",job=\"fabric\",stats=\"webserviceCalls\", env=\"$Environment\"}[5m]))))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Failed API Calls Count",
   "type": "stat",
   "description": "The number of Web Service Errors that occurred in the last 5 minutes.\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\n",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(com_k2view_fabric_stats_count{category=\"transactions\", stats=\"webserviceErrors\", key=~\"[Kk]2.*\", env=\"$Environment\"}[5m]))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "API Calls",
   "type": "timeseries",
   "description": "Number of Web Service Calls per API in the last 5 minutes.\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\nYou can set a larger time range from the top right of Grafana and the time series will expand.\n",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((sum by (key) (increase(com_k2view_fabric_stats_count{category=\"transactions\",key=~\"[Kk]2.*\",job=\"fabric\",stats=\"webserviceCalls\", env=\"$Environment\"}[5m]))))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "API Calls Avg. Response Time",
   "type": "timeseries",
   "description": "Response times of Web Services per API, in the last 5 minutes.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\nThresholds can be set.\nYou can set a larger time range from the top right of Grafana and the time series will expand.\n",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(avg by (key) (increase(com_k2view_fabric_stats_total{category=\"transactions\",key=~\".*\",stats=\"webserviceCalls\",key!=\"\", env=\"$Environment\"}[5m])))  /(avg by (key) (increase(com_k2view_fabric_stats_count{category=\"transactions\",key=~\".*\",job=\"fabric\",stats=\"webserviceCalls\", key!=\"\", env=\"$Environment\"}[5m])))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "API Calls Failures",
   "type": "timeseries",
   "description": "The number of Web Service Errors that occurred in the last 5 minutes for each api.\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nJMX should be running in order for this metric to work. If JMX is running and you get no data from those metrics, double check the JMX configuration blacklist, or load the default configuration.\n",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (key)(increase(com_k2view_fabric_stats_count{category=\"transactions\", stats=\"webserviceErrors\", key=~\"[Kk]2.*\", env=\"$Environment\"}[5m]))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Fabric Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Fabric Logs",
     "type": "logs",
     "description": "Read the instructions below this metric to set it up correctly.\n",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "{filename=\"/opt/apps/k2view/logs/k2fabric.log\"}"
      }
     ]
    }
   ]
  },
  { "title": "Cassandra Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Cassandra Nodes Up",
   "type": "stat",
   "description": "Cassandra Nodes Up\nEnter the proper variables on the top side of the dashboard.\nIf needed, Modify the query to return your cassandra nodes.\nAlter the Threshold Green Value to the amount of nodes of Cassandra.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\".*$CassandraPort\", job=\"cassandra\", env=\"$Environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cassandra Average CPU Usage",
   "type": "stat",
   "description": "Average CPU Usage of the Cassandra Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nNode Exporter should be running in order for this metric to work.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100-(avg by(node) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"cassandra\", env=\"$Environment\"}[5m]))*100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cassandra Average Memory Usage",
   "type": "stat",
   "description": "Average Memory(RAM) Usage of the Cassandra Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nNode Exporter should be running in order for this metric to work.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_memory_MemAvailable_bytes{node=~\"cn_.*\", env=\"$Environment\"} * 100) / node_memory_MemTotal_bytes{node=~\"cn_.*\", env=\"$Environment\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cassandra Average Heap Usage",
   "type": "stat",
   "description": "Average Heap Memory Usage of the Cassandra Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nNode Exporter should be running in order for this metric to work.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{area=\"heap\", instance=~\".*$CassandraPort\", env=\"$Environment\"}/jvm_memory_bytes_max{area=\"heap\", instance=~\".*$CassandraPort\", env=\"$Environment\"}*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cassandra Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Cassandra Disk Usage Top 5",
   "type": "stat",
   "description": "This metric can't be made into a time-series.\nNode Exporter and JMX Exporter need to run on the Cassandra Machines in order to retrieve proper data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,(100 - ((node_filesystem_avail_bytes{mountpoint=~\".*cassandra.*\", env=\"$Environment\"} * 100)/  node_filesystem_size_bytes{mountpoint=~\".*cassandra.*\", env=\"$Environment\"})))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cassandra Pending Top 5 Compactions ",
   "type": "stat",
   "description": "This metric can't be made into a time-series.\nNode Exporter and JMX Exporter need to run on the Cassandra Machines in order to retrieve proper data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,(org_apache_cassandra_metrics_Compaction_Value{instance=~\".*:$CassandraPort\",name=\"PendingTasks\", env=\"$Environment\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cassandra Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cassandra Errors",
     "type": "stat",
     "description": "The Job inside Cassandra Logs should match the following regex: *cassandra*\nFor information on how to change this, consult the fabric logs instructions and extrapolate to the Cassandra Machines.\nTo set up this metric correctly, follow the fabric instructions, but apply them for cassandra. Name the job title for the cassandra machines using the same convention as for the fabric.\nThe query for the cassandra logs is different because cassandra directories tend to differ by project. This query uses more processing power, so you may want to change the query to this example, adjusted for your environment:\nfilename=\"/opt/apps/cassandra/logs/system.log\".",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max((count_over_time({job=~\".*cassandra.*\"} |= \"ERROR\" [5m])))",
       "legendFormat": "ERRORS"
      }
     ]
    },
    {
     "title": "Cassandra Logs",
     "type": "logs",
     "description": "The Job inside Cassandra Logs should match the following regex: *cassandra*\nFor information on how to change this, consult the fabric logs instructions and extrapolate to the Cassandra Machines.\nTo set up this metric correctly, follow the fabric instructions, but apply them for cassandra. Name the job title for the cassandra machines using the same convention as for the fabric.\nThe query for the cassandra logs is different because cassandra directories tend to differ by project. This query uses more processing power, so you may want to change the query to this example, adjusted for your environment:\nfilename=\"/opt/apps/cassandra/logs/system.log\".",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "{job=~\".*cassandra.*\"}"
      }
     ]
    }
   ]
  },
  { "title": "Kafka Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Kafka Nodes Up",
   "type": "stat",
   "description": "Kafka Nodes Up\nEnter the proper variables on the top side of the dashboard.\nIf needed, Modify the query to return your kafka nodes.\nAlter the Threshold Green Value to the amount of nodes of Kafka.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\".*$KafkaPort\", job=\"kafka\", env=\"$Environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Average CPU Usage",
   "type": "stat",
   "description": "Average CPU Usage of the Kafka Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nNode Exporter should be running in order for this metric to work.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100-(avg by(node) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"kafka\", env=\"$Environment\"}[5m]))*100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Average Memory Usage",
   "type": "stat",
   "description": "Average Memory(RAM) Usage of the Kafka Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nNode Exporter should be running in order for this metric to work.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_memory_MemAvailable_bytes{node=~\"kn_.*\", env=\"$Environment\"} * 100) / node_memory_MemTotal_bytes{node=~\"kn_.*\", env=\"$Environment\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Average Heap Usage",
   "type": "stat",
   "description": "Average Heap Memory Usage of the Kafka Nodes\nAlter the Threshold Red/Yellow Values to the desired thresholds.\nNode Exporter should be running in order for this metric to work.\nThe \"avg\" at the start of the query can be set to \"min\" or \"max\" to display different calculations of the values we are receiving.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{area=\"heap\", instance=~\".*$KafkaPort\"}/jvm_memory_bytes_max{area=\"heap\", instance=~\".*$KafkaPort\"}*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka Performance ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Kafka Disk Usage Top 5",
   "type": "stat",
   "description": "This metric can't be made into a time-series.\nNode Exporter and JMX Exporter need to run on the Kafka Machines in order to retrieve proper data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,(100 - ((node_filesystem_avail_bytes{mountpoint=~\".*kafka.*\", env=\"$Environment\"} * 100)/  node_filesystem_size_bytes{mountpoint=~\".*kafka.*\", env=\"$Environment\"})))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Kakfa Messages per Topic per Second in the last 5 minutes.",
   "type": "stat",
   "description": "This metric can't be made into a time-series.\nNode Exporter and JMX Exporter need to run on the Kafka Machines in order to retrieve proper data. \nTo avoid clutter, only topics that receive messages are shown.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(kafka_server_messages_in_per_sec_per_topic{job=\"kafka\", env=\"$Environment\"}[10m]) > 1",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Errors",
     "type": "stat",
     "description": "The Job inside Kafka Logs should match the following regex: *kafka*\nFor information on how to change this, consult the fabric logs instructions and extrapolate to the Kafka Machines.\nTo set up this metric correctly, follow the fabric instructions, but apply them for kafka. Name the job title for the kafka machines using the same convention as for the fabric.\nThe query for the kafka logs is different because kafka directories tend to differ by project. This query uses more processing power, so you may want to change the query to this example, adjusted for your environment:\nfilename=\"/opt/apps/kafka/logs/system.log\".",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max((count_over_time({job=~\".*kafka.*\"} |= \"ERROR\" [5m])))",
       "legendFormat": "ERRORS"
      }
     ]
    },
    {
     "title": "Kakfa Logs",
     "type": "logs",
     "description": "The Job inside Kafka Logs should match the following regex: *kafka*\nFor information on how to change this, consult the fabric logs instructions and extrapolate to the Kafka Machines.\nTo set up this metric correctly, follow the fabric instructions, but apply them for kafka. Name the job title for the kafka machines using the same convention as for the fabric.\nThe query for the kafka logs is different because kafka directories tend to differ by project. This query uses more processing power, so you may want to change the query to this example, adjusted for your environment:\nfilename=\"/opt/apps/kafka/kafka/logs/server.log\".",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "{job=~\".*kafka.*\"}"
      }
     ]
    }
   ]
  }
 ]
}