
 -- Role: "BILLING_USER"
-- DROP ROLE "BILLING_USER";

CREATE ROLE "BILLING_USER" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md5eba27c06967d09bc1279ad8c0c6bbf38';
 
-- Role: "COLLECTION_USER"
-- DROP ROLE "COLLECTION_USER";
 CREATE ROLE "COLLECTION_USER" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md5204b72d5ca793cc87cc8d8f1a5dac207';
 
 -- Role: "ORDERS_USER"
-- DROP ROLE "ORDERS_USER";

CREATE ROLE "ORDERS_USER" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md59da2b75067b9d9ce85f4dd5622e98728';
  
-- Role: "CRM_USER"
-- DROP ROLE "CRM_USER";

CREATE ROLE "CRM_USER" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md5bcd7344a6026876520c43970d3e14c8b';

-- Role: "TAR_BILLING_USER"
-- DROP ROLE "TAR_BILLING_USER";

CREATE ROLE "TAR_BILLING_USER" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md5666569fd4c4b9c82e9a63e0f4b90f36d';
 
 -- Role: "TAR_COLLECTION_USER"
-- DROP ROLE "TAR_COLLECTION_USER";

CREATE ROLE "TAR_COLLECTION_USER" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md5731ed3d1123d8015377d23f075d7a745';
 
 -- Role: "TAR_ORDERING_USER"
-- DROP ROLE "TAR_ORDERING_USER";

CREATE ROLE "TAR_ORDERING_USER" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md58600829010054c151c1924b4ee79eb32';
  
  -- Role: "TAR_CRM_USER"
-- DROP ROLE "TAR_CRM_USER";

-- Role: "TAR_CRM_USER"
-- DROP ROLE "TAR_CRM_USER";

CREATE ROLE "TAR_CRM_USER" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md5b6228bd0af1b584619b2ba3a9a7afaff';
 
 -- Database: BILLING_DB

-- DROP DATABASE "BILLING_DB";

CREATE DATABASE "BILLING_DB"
    WITH 
    OWNER = "BILLING_USER"
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
   
   -- Database: COLLECTION_DB

-- DROP DATABASE "COLLECTION_DB";

CREATE DATABASE "COLLECTION_DB"
    WITH 
    OWNER = "COLLECTION_USER"
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
   
   -- Database: ORDERING_DB

-- DROP DATABASE "ORDERING_DB";

CREATE DATABASE "ORDERING_DB"
    WITH 
    OWNER = "ORDERS_USER"
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
   
   -- Database: TAR_BILLING_DB

-- DROP DATABASE "TAR_BILLING_DB";

CREATE DATABASE "TAR_BILLING_DB"
    WITH 
    OWNER = "TAR_BILLING_USER"
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
   
   -- Database: TAR_COLLECTION

-- DROP DATABASE "TAR_COLLECTION";

CREATE DATABASE "TAR_COLLECTION"
    WITH 
    OWNER = "TAR_COLLECTION_USER"
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
   
   -- Database: TAR_ORDERING

-- DROP DATABASE "TAR_ORDERING";

CREATE DATABASE "TAR_ORDERING"
    WITH 
    OWNER = "TAR_ORDERING_USER"
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
	-- Database: CRM_DB

-- DROP DATABASE "CRM_DB";

CREATE DATABASE "CRM_DB"
    WITH 
    OWNER = "CRM_USER"
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

-- Database: TAR_CRM_DB

-- DROP DATABASE "TAR_CRM_DB";

CREATE DATABASE "TAR_CRM_DB"
    WITH 
    OWNER = "TAR_CRM_USER"
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;